apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::658775564324:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-mVv8kZdV4rzG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::658775564324:user/trinath
      username: trinath
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-02T02:02:22Z"
  name: aws-auth
  namespace: kube-system
  uid: d12925de-ff72-488e-8613-195d1e21b6dd

